global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'spark-driver'
    metrics_path: '/metrics/prometheus'
    static_configs:
      - targets: ['localhost:4040']
        labels:
          component: 'driver'
  - job_name: 'spark-executors'
    gcp_sd_configs:
      - project: '-gcp-project-id'
        zone: 'us-central1-a'
        filter: 'labels.goog-dataproc-cluster-name = dataproc-cluster'
        port: 4040
    relabel_configs:
      - source_labels: [__meta_gcp_metadata_role]
        regex: 'Worker'
        action: keep
      - target_label: job
        replacement: 'spark-executors'
      - source_labels: [__address__, __meta_gcp_instance_name]
        target_label: instance
        replacement: '$1 ($2)'
      - source_labels: [__meta_gcp_metadata_preemptible]
        target_label: lifecycle
        regex: 'true'
        replacement: 'spot'
      - source_labels: [__meta_gcp_metadata_preemptible]
        target_label: lifecycle
        regex: 'false'
        replacement: 'on-demand'
    metrics_path: '/metrics/prometheus'
  - job_name: 'spark-streaming'
    metrics_path: '/metrics/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:4040']
        labels:
          app: 'streaming'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'spark_streaming_.*'
        action: keep
